import LayoutProvider from '@/components/LayoutProvider'
import './globals.css'
import type { Metadata } from 'next'

import '../stylesheets/commonClasses.css'
import '../stylesheets/antdOverwrite.css'
import '../stylesheets/layout.css'
import "../stylesheets/loader.css"
import ReduxProvider from '@/components/ReduxProvider'

export const metadata: Metadata = {
  title: 'Apply Jobs',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReduxProvider>
      <LayoutProvider>{children}</LayoutProvider>
    </ReduxProvider>
  );
}
